# Use Python as the base image
FROM python:3.9


# Set the working directory
WORKDIR /app

# Copy your actions and requirements
COPY ./actions /app/actions
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt
# Expose the default port for the Action Server
EXPOSE 5055

# Command to run the Rasa action server
CMD ["rasa", "run", "actions"]
#CMD ["start", "--actions", "actions"]